### ISSUE TITLE
Exception occur on project Run

### ISSUE THREAD

**Issue by Scienticious** [m-hamzashakeel/The_Holy_Quran_App#1]
FlutterError (Unable to load asset: assets/grad_logo.png)
File Name : image_provider.dart
Line # 672

**Comment by m-hamzashakeel** [comment]
![grad_logo](https://user-images.githubusercontent.com/43790152/90263760-899e3280-de69-11ea-816d-04f49755e6e9.png)
Sorry For the issue
actually I didn't updated the image you can use this and place it in ```assets```
thanks

**Comment by Scienticious** [comment]
@m-hamzashakeel ,
I have placed the assests folder but when I about to run the app I got the following error.

Unable to load asset: assets/quranRail.png
Unable to load asset: assets/myPic.JPG
 Unable to load asset: assets/quranRail.png
Unable to load asset: assets/kaaba.png

**Comment by m-hamzashakeel** [comment]
![quranRail](https://user-images.githubusercontent.com/43790152/90405743-a2068b00-e0bd-11ea-806f-1e29f90352c0.png)


![kaaba](https://user-images.githubusercontent.com/43790152/90405751-a468e500-e0bd-11ea-98b4-cca04a5fd18f.png)


For mypic.png you can use your own pic

**Comment by Scienticious** [comment]
@m-hamzashakeel  I have fixed this issue and raised a Pull Request,
could you please merge my code.
