### ISSUE TITLE
build.gradle' line: 56

### ISSUE THREAD

**Issue by wafahas** [m-hamzashakeel/The_Holy_Quran_App#3]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/wafaaabudawod/AndroidStudioProjects/The_Holy_Quran_App-master/android/app/build.gradle' line: 56

* What went wrong:
A problem occurred evaluating project ':app'.
> Cannot convert URL 'D:/_keys/alquran.jks' to a file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by shameemreza** [comment]
remove these from build.gradle:

`    signingConfigs {
       release {
           storeFile file(keystoreProperties['storeFile'])
           storePassword keystoreProperties['storePassword']
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
       }
    }`

**Comment by wafahas** [comment]
could you please provide me with the textbook or course that can help me to
build like your app

**Comment by m-hamzashakeel** [comment]
@wafahas If you are looking for a guide you can use this `https://github.com/m-hamzashakeel/Flutter-Roadmap-and-Resources-Guide` i have mentioned a detailed article in the start which might help you as well :)
Good luck

**Comment by shameemreza** [comment]
You will get lot of good course out there. Most of the best resources are mentioned in @m-hamzashakeel roadmap guide. You also may check on YouTube as well.
