### ISSUE TITLE
How are you handling the uStrings?

### ISSUE THREAD

**Issue by AhyaanTech** [m-hamzashakeel/The_Holy_Quran_App#4]
Hello was using ur project as a guide

"\u0627\u0644\u0651\u064e\u0630\u0650\u064a \u064a\u064f\u0648\u064e\u0633\u0652\u0648\u0650\u0633\u064f \u0641\u0650\u064a \u0635\u064f\u062f\u064f\u0648\u0631\u0650 \u0627\u0644\u0646\u0651\u064e\u0627\u0633\u0650"

That is the text that i returned from the api. how are you converting that to arabic text?

**Comment by m-hamzashakeel** [comment]
I think you are passing the string in double commas `Text(" ")` instead remove those double commas keep it simple like this `Text ( ) `

**Comment by AhyaanTech** [comment]
Oh flutter itself handles the decoding?

**Comment by AhyaanTech** [comment]
Any idea how to get individual words?

**Comment by m-hamzashakeel** [comment]
Yes, flutter handles the decode

For single word I'm not sure probably u have to do something related to getting substrings
